version: '3'
services:
  mc:
    build: 
      context: .
      dockerfile: ./docker/mc/Dockerfile
    depends_on:
      - "mysql"
    environment:
      - "MYSQL_URL=mysql:3306"
      - "MYSQL_USER=${MYSQL_USER}"
      - "MYSQL_PASSWORD=${MYSQL_PASSWORD}"
      - "MYSQL_DATABASE=${MYSQL_DATABASE}"
  mcweb:
    build: 
      context: .
      dockerfile: ./docker/mcweb/Dockerfile
    depends_on:
      - "mysql"
    ports:
      - "5000:5000"
    environment:
      - "MYSQL_URL=mysql:3306"
      - "MYSQL_USER=${MYSQL_USER}"
      - "MYSQL_PASSWORD=${MYSQL_PASSWORD}"
      - "MYSQL_DATABASE=${MYSQL_DATABASE}"
  mysql:
    image: "mysql:5.7"
    restart: always
    ports:
      - "3306:3306"
    environment:
      - "MYSQL_ROOT_PASSWORD=${MYSQL_ROOT_PASSWORD}"
      - "MYSQL_USER=${MYSQL_USER}"
      - "MYSQL_PASSWORD=${MYSQL_PASSWORD}"
      - "MYSQL_DATABASE=${MYSQL_DATABASE}"
    volumes:
      - "./scripts/mysql/custom.cnf:/etc/mysql/conf.d/custom.cnf"
      - "./scripts/mysql/docker-entrypoint-initdb.d:/docker-entrypoint-initdb.d"
