version: '3'
services:
  ubuntu:
    image: "ubuntu:18.04"
    volumes:
      - "./bin/linux:/command"
    entrypoint: /command/metrics-collector
    depends_on:
      - "mysql"
    environment:
      - "MYSQL_URL=${MYSQL_URL}"
      - "MYSQL_USER=${MYSQL_USER}"
      - "MYSQL_PASSWORD=${MYSQL_PASSWORD}"
      - "MYSQL_DATABASE=${MYSQL_DATABASE}"
  mysql:
    image: "mysql:5.7"
    restart: always
    ports:
      - "3306:3306"
    environment:
      - "MYSQL_ROOT_PASSWORD=${MYSQL_ROOT_PASSWORD}"
      - "MYSQL_USER=${MYSQL_USER}"
      - "MYSQL_PASSWORD=${MYSQL_PASSWORD}"
      - "MYSQL_DATABASE=${MYSQL_DATABASE}"
    volumes:
      - "./scripts/mysql/custom.cnf:/etc/mysql/conf.d/custom.cnf"
      - "./scripts/mysql/docker-entrypoint-initdb.d:/docker-entrypoint-initdb.d"
